apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: my-golang-app
        image: my-golang-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
